spring:
  datasource:
    type: ${mysql.type}
    driver-class-name: ${mysql.driver-class-name}
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID