spring:
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      timeout: 10000
      database: 1
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0